name: 'skopeo-setup-action'
description: 'Setup Skopeo'
author: contact@lemondouble.com
branding:
  color: yellow
  icon: download-cloud

inputs:
  version:
    description: 'Version of skopeo to install'
    required: false
    default: 'v1.18.0'

runs:
  using: "composite"
  steps:
    - name: setup items
      shell: bash
      run: sudo apt update -y && sudo apt install wget -y

    - name: Determine architecture and set ARCH variable
      id: determine_arch
      shell: bash
      run: |
        current_arch=$(arch)
        if [[ "$current_arch" == "x86_64" ]]; then
          echo "ARCH=amd64" >> $GITHUB_ENV
        elif [[ "$current_arch" == "aarch64" || "$current_arch" == "arm64" ]]; then
          echo "ARCH=arm64" >> $GITHUB_ENV
        else
          echo "Unsupported architecture: $current_arch" >&2
          exit 1
        fi

    - name: Download skopeo binary
      shell: bash
      run: sudo wget https://github.com/lework/skopeo-binary/releases/download/${{ inputs.version }}/skopeo-linux-${ARCH} -O /usr/bin/skopeo

    - name: Set execute permissions for skopeo
      shell: bash
      run: sudo chmod +x /usr/bin/skopeo

    - name: Download Default Policy
      shell: bash
      run: | 
        mkdir -p ~/.config/containers
        sudo wget https://raw.githubusercontent.com/LemonDouble/setup-skopeo/refs/heads/main/default-policy.json -O ~/.config/containers/policy.json